snakefile: Snakefile
show-failed-logs: True
keep-going: True
retries: 3
rerun-incomplete: True
jobs: 100
cluster: "sbatch --account berglandlab -p standard -o {resources.log_dir}/{rule}.%A.out -e {resources.log_dir}/{rule}.%A.err -J {rule} --ntasks-per-node={resources.ntasks_per_node} -N 1 -t {resources.time_limit} --mem {resources.memory_limit}G --parsable"
cluster-status: ~/CompEvoBio_modules/utils/snpCallingslurm/slurm_job_status.sh
default-resources: [ntasks_per_node=4, memory_limit=48, time_limit=180]
